- name: copy bash_aliases
  copy:
    src: "data/.bash_aliases"
    dest: "/home/{{user}}/"
- name: copy tmux conf
  copy:
    src: "data/.tmux.conf"
    dest: "/home/{{user}}/"
- name: copy i3 conf
  copy:
    src: "data/config"
    dest: "/home/{{user}}/.config/i3/"
- name: copy run_coppeliasim
  copy:
    src: "data/run_coppeliasim"
    dest: "/usr/local/bin/"
- name: copy run_rviz2
  copy:
    src: "data/run_rviz2"
    dest: "/usr/local/bin/"
- name: copy setdpisfb
  copy:
    src: "data/setdpisfb"
    dest: "/usr/local/bin/"
