---
- hosts: localhost
  roles:
  - role: gantsign.visual-studio-code
    become: yes
    become_user: root
  - role: geerlingguy.docker
    become: yes
    become_user: root
  tasks:
  - name: show current user
    debug:
      msg: "installing for user: {{ansible_user_id}}"
  - import_tasks: tasks/basic.yml
  - import_tasks: tasks/simpleterm.yml
  - import_tasks: tasks/myconfig.yml
  - import_tasks: tasks/ros-humble.yml
  - import_tasks: tasks/tufast.yml
  - import_tasks: tasks/specific.yml
