- name: basic - Install basic components
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - neovim
    - i3
    - tmux
    - htop
    - xclip
    - links
    - iftop
    - rsync
    - maim
  become: true
  become_user: root