- name: muc-startup - Set dependencies variable
  set_fact:
    muc_repo_dir: "/home/{{ansible_user_id}}/muc022-startup"

- name: muc-startup - Install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - git-lfs
    - python3-termcolor
  become_user: root

- name: muc-startup - Clone repo locally.
  git:
    repo: "git@gitlab.lrz.de:tufast-eco-fallback/muc022-startup.git"
    dest: "{{ muc_repo_dir }}"
    version: "ros2_ubuntu22"
    recursive: yes
    update: yes
    accept_hostkey: yes
    
- name: muc-startup - Fix start.sh docker compose
  shell: "sed -i 's/ docker-compose / docker compose /g' unified/start.sh"
  args:
    chdir: "{{muc_repo_dir}}"
    executable: /bin/bash
