- name: myconfig - copy configs to user folder
  copy:
    src: "{{item}}"
    dest: "/home/{{ansible_user_id}}/"
  with_items:
    - "data/.bash_aliases"
    - "data/.tmux.conf"
    - "data/.bashrc"

- name: myconfig - copy i3 conf
  copy:
    src: "{{item}}"
    dest: "/home/{{ansible_user_id}}/.config/i3/"
  with_items:
    - "data/i3/config"
    - "data/muc023_france.jpg"

- name: myconfig - copy sway conf
  copy:
    src: "{{item}}"
    dest: "/home/{{ansible_user_id}}/.config/sway/"
  with_items:
    - "data/sway/config"
    - "data/muc023_france.jpg"

- name: myconfig - run scripts
  become_user: root
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/"
    mode: preserve
  with_items:
    - "data/backlight"
    - "data/run_coppeliasim"
    - "data/run_rviz2"
    - "data/setdpisfb"
    - "data/run_reconfigure"
    - "data/share_internet"
