- name: copy configs to user folder
  copy:
    src: "{{item}}"
    dest: "/home/{{user}}/"
  with_items:
    - "data/.bash_aliases"
    - "data/.tmux.conf"
- name: copy i3 conf
  copy:
    src: "data/config"
    dest: "/home/{{user}}/.config/i3/"
- name: run scripts
  become: true
  become_user: root
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/"
    mode: preserve
  with_items:
    - "data/run_coppeliasim"
    - "data/run_rviz2"
    - "data/setdpisfb"
    - "data/run_reconfigure"
    - "data/share_internet"
