- name: myconfig - copy configs to user folder
  copy:
    src: "{{item}}"
    dest: "/home/{{ansible_user_id}}/"
  with_items:
    - "data/.bash_aliases"
    - "data/.tmux.conf"

- name: myconfig - copy i3 conf
  copy:
    src: "data/config"
    dest: "/home/{{ansible_user_id}}/.config/i3/"

- name: myconfig - run scripts
  become_user: root
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/"
    mode: preserve
  with_items:
    - "data/run_coppeliasim"
    - "data/run_rviz2"
    - "data/setdpisfb"
    - "data/run_reconfigure"
    - "data/share_internet"
    - "data/backlight"
