---
# sudo apt update && sudo apt install curl gnupg2 lsb-release
- name: Install dependencies for setting up sources
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - gnupg2
    - lsb-release
  become: yes
  become_user: root

# curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
- name: Setup ROS2 keys
  apt_key:
    url: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
    state: present
  become: yes
  become_user: root

# sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
- name: Setup ROS2 sources
  apt_repository:
    repo: "deb http://packages.ros.org/ros2/ubuntu jammy main"
    state: present
    filename: ros2-latest
  become: yes
  become_user: root

# sudo apt install ros-<distro>-ros-base
- name: Install ROS2
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - "ros-humble-desktop"
      - "ros-dev-tools"
  become: yes
  become_user: root