- name: rtl8821 - set variables
  set_fact:
    rtl8812au_repo_locations: "/tmp/rtl8821-au"
- name: rtl8821au - install deps
  apt: 
    name: "{{item}}"
  with_items:
    - build-essential
    - dkms
    - git
    - iw
  become_user: root
- name: rtl8821au - clone driver
  git:
    repo: "https://github.com/kmodexc/8821au-20210708.git"
    dest: "{{ rtl8812au_repo_locations }}"
    version: "main"
    accept_hostkey: false
- name: rtl8821au - build and install
  shell: |
    ./install-driver.sh
  args:
    chdir: "{{ rtl8812au_repo_locations }}"
  become_user: root
