- name: specific - install specific deps
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xbindkeys
    - xsel
    - xdotool
- name: specific - set default target to console
  become: true
  become_user: root
  shell: "systemctl set-default multi-user.target"
- name: specific -  grub to show boot log
  become: true
  become_user: root
  shell: "sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\\\"\\\"/g' /etc/default/grub && update-grub"
- name: specific - set natural scrolling
  become: true
  become_user: root
  copy:
    src: "data/30-touchpad.conf"
    dest: "/etc/X11/xorg.conf.d/"
- name: specific - set gtk darktheme
  copy: 
    src: "data/settings.ini"
    dest: "/home/{{ansible_user_id}}/.config/gtk-{{item}}/"
  with_items:
    - "3.0"
    - "4.0"
- name: specific - set xterm to dark mode
  copy:
    src: data/.Xdefaults
    dest: /home/{{ansible_user_id}}/
- name: specific - disable middle click paste - copy config
  copy:
    src: data/.xbindkeysrc
    dest: /home/{{ansible_user_id}}/
- name: specific - disable middle click paste - start xbindkeyrc at i3 start
  copy:
    src: data/.xprofile
    dest: /home/{{ansible_user_id}}/
- name: specifig - set colcon to not send notifications
  copy:
    src: data/.bashrc
    dest: /home/{{ansible_user_id}}/
    
